---
version: "2.1"
services:
  guacamole:
    image: oznu/guacamole
    container_name: guacamole
    hostname: guacamole
    networks:
      - fak-bridge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - EXTENSIONS=auth-ldap
    volumes:
      - guacamole_data:/config
    labels:
      traefik.enable: 'true'
      traefik.http.routers.guacamole.entrypoints: websecure
      traefik.http.routers.guacamole.rule: Host(`guacamole.${DOMAIN}`)
      traefik.http.routers.guacamole.tls: 'true'
      traefik.http.routers.guacamole.service: guacamole
      traefik.http.services.guacamole.loadbalancer.server.port: 8080
    restart: unless-stopped
volumes:
  guacamole_data:
networks:
  fak-bridge:
    external:
      name: ${NETWORK_NAME}
