---
version: "2"
services:
  nextcloud:
    image: nextcloud:22.0.0-fpm
    container_name: nextcloud
    hostname: nextcloud
    links:
      - nextcloud_db
    depends_on:
      - nextcloud_db
    networks:
      - fak-bridge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_PASSWORD}
#      - SQLITE_DATABASE=nextcloud_sql
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mariadb
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - nextcloud_data:/var/www/html
    labels:
      traefik.enable: 'true'
      traefik.http.routers.nextcloud.entrypoints: websecure
      traefik.http.routers.nextcloud.rule: Host(`nextcloud.${DOMAIN}`)
      traefik.http.routers.nextcloud.tls: 'true'
      traefik.http.routers.nextcloud.service: nextcloud
      traefik.http.services.nextcloud.loadbalancer.server.port: 9000
#      traefik.http.services.nextcloud.loadbalancer.server.scheme: https
    restart: unless-stopped
  nextcloud_db:
    image: mariadb:10.3.22
    container_name: nextcloud_db
    hostname: mariadb
    networks:
      - fak-bridge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - nextcloud_db:/var/lib/mysql
    restart: unless-stopped
volumes:
  nextcloud_data:
  nextcloud_db:
networks:
  fak-bridge:
    external:
      name: ${NETWORK_NAME}
